print("Bienvenido a GymLab")
nombre = input ("¿cual es tu nombre? ")
print(f"¡mucho gusto, {nombre}!")
print("Para comenzar necesito que me dejes tus datos")
dni = input ("DNI: ")
actividad = input ("¿A qué actividad te gustaria anotarte? ")
membresia = input ("¿Cuántos días a la semana te gustaria venir? ")
print("¡Genial, comencemos!")
print(f"Ficha creada: {nombre} - DNI: {dni} - Clase: {actividad} ({membresia} días).")
